version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      open-pull-reauests-limit: 1
      rebase-strategy: "auto"
      groups:
        all-dependencies:
          patterns
            - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      versioning-strategy: lockfile-only
      open-pull-requests-limit: 1
      rebase-strategy: "auto"
      groups:
        # split intp groups by dev and prod
        minor-production-dependencies:
          dependency-type: "production"
          update-types:
            - minor
            - patch
        minor-development-dependencies:
          dependency-type: "development"
          update-types:
            - minor
            - patch

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      target-branch: "main"
      open-pull-requests-limit: 1
      rebase-strategy: "auto"
      groups:
        # split intp groups by dev and prod
        major-production-dependencies:
          dependency-type: "production"
          update-types:
            - major
        major-development-dependencies:
          dependency-type: "development"
          update-types:
            - major
